name: Fetch Static Secrets

on: 
  push: 

jobs:
  fetch_secrets:
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Debugging Info - Start
      run: |
        echo "Debug: Starting Fetch Static Secrets job"
        echo "Debug: GitHub Actor - ${{ github.actor }}"
        echo "Debug: GitHub Repository - ${{ github.repository }}"
        echo "Debug: GitHub Event Name - ${{ github.event_name }}"
    
    - name: Fetch static secrets from Akeyless
      uses: akeyless-community/akeyless-github-action@v1.0.1
      id: fetch-secrets
      with:
        access-id: '${{ secrets.ACCESS_ID }}'
        access-type: jwt
        export-secrets-to-outputs: true
        export-secrets-to-environment: true
        static-secrets: |
          - name: "/SJ-Test-Static-Key"
            output-name: "my_first_secret"
        api-url: "https://csm.thalescryptolabs.com/akeyless-api/v2"
    
    - name: Debugging Info - After Fetch
      run: |
        echo "Debug: Fetched Secret Output Name - my_first_secret = ${{ steps.fetch-secrets.outputs.my_first_secret }}"
        echo "Debug: Fetched Secret Environment Variable - my_first_secret = ${{ env.my_first_secret }}"
        env
    
    - name: Use Akeyless secret (environment variable)
      env:
        SECRET: ${{ env.my_first_secret }}
      run: |
        # Use the secret securely within this step
        echo "Doing something with $SECRET"
     
    - name: Use Akeyless secret (step output)
      run: |
        # Use the secret securely within this step
        echo "Doing something with ${{ steps.fetch-secrets.outputs.my_first_secret }}"
    
    - name: Debugging Info - End
      run: echo "Debug: Finished Fetch Static Secrets job"
